from __future__ import annotations

import json

from webbuilder.models import JsonDict


def render(requirements: JsonDict, plan: JsonDict) -> dict[str, str]:
    website_type = str(requirements.get("website_type", "SaaS App")).replace("_", " ").title()
    theme = str(requirements.get("theme", "modern"))
    components = requirements.get("components", ["Navbar", "Hero", "Features", "Pricing", "Contact", "Footer"])
    sections = plan.get("sections", ["hero", "features", "pricing", "contact"])

    package_json = {
        "name": "generated-app",
        "version": "0.1.0",
        "private": True,
        "scripts": {
            "dev": "next dev",
            "build": "next build",
            "start": "next start",
            "lint": "next lint",
        },
        "dependencies": {
            "next": "latest",
            "react": "latest",
            "react-dom": "latest",
        },
        "devDependencies": {
            "@types/node": "latest",
            "@types/react": "latest",
            "@types/react-dom": "latest",
            "typescript": "latest",
            "tailwindcss": "latest",
            "postcss": "latest",
            "autoprefixer": "latest",
        },
    }

    tsconfig_json = {
        "compilerOptions": {
            "target": "ES2017",
            "lib": ["dom", "dom.iterable", "esnext"],
            "allowJs": True,
            "skipLibCheck": True,
            "strict": True,
            "noEmit": True,
            "esModuleInterop": True,
            "module": "esnext",
            "moduleResolution": "bundler",
            "resolveJsonModule": True,
            "isolatedModules": True,
            "jsx": "preserve",
            "incremental": True,
            "plugins": [{"name": "next"}],
            "paths": {"@/*": ["./src/*"]},
        },
        "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
        "exclude": ["node_modules"],
    }

    tailwind_config = f"""/** @type {{import('tailwindcss').Config}} */
module.exports = {{
  content: [
    './src/pages/**/*.{'{'}js,ts,jsx,tsx,mdx{'}'}',
    './src/components/**/*.{'{'}js,ts,jsx,tsx,mdx{'}'}',
    './src/app/**/*.{'{'}js,ts,jsx,tsx,mdx{'}'}',
  ],
  theme: {{
    extend: {{}},
  }},
  plugins: [],
}}
"""

    postcss_config = """module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
"""

    layout_tsx = """import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: '""" + website_type + """',
  description: 'Generated by WebForge autonomous builder',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
"""

    globals_css = """@tailwind base;
@tailwind components;
@tailwind utilities;

body {
  font-family: system-ui, -apple-system, sans-serif;
}
"""

    features_str = json.dumps([
        "Autonomous repair loop",
        "Multi-agent collaboration",
        "Template-guided generation",
        "Live local preview",
    ])

    page_tsx = f"""'use client';

import {{ ArrowRight, Check, Mail, Sparkles, Zap }} from 'lucide-react';

const features = {features_str};
const sections = {json.dumps(sections)};

export default function Home() {{
  return (
    <main className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-slate-100">
      <nav className="flex items-center justify-between max-w-7xl mx-auto px-6 py-5">
        <div className="flex items-center gap-2 font-bold text-xl text-slate-900">
          <Sparkles className="w-5 h-5 text-blue-600" /> {website_type}
        </div>
        <div className="hidden md:flex items-center gap-8">
          <a href="#features" className="text-sm text-slate-500 hover:text-slate-900 transition-colors">Features</a>
          <a href="#pricing" className="text-sm text-slate-500 hover:text-slate-900 transition-colors">Pricing</a>
          <a href="#contact" className="text-sm text-slate-500 hover:text-slate-900 transition-colors">Contact</a>
        </div>
      </nav>

      <section className="max-w-7xl mx-auto px-6 py-20 grid md:grid-cols-2 gap-12 items-center">
        <div>
          <span className="text-xs font-bold uppercase tracking-widest text-blue-600">{theme} web engineering</span>
          <h1 className="mt-4 text-5xl md:text-6xl font-bold leading-tight text-slate-900">
            Ship polished web pages with local AI agents.
          </h1>
          <p className="mt-6 text-lg text-slate-500 leading-relaxed max-w-lg">
            A focused autonomous builder that plans, generates, validates, repairs,
            and previews production-ready Next.js interfaces from a single prompt.
          </p>
          <div className="mt-8 flex flex-wrap gap-4">
            <a href="#contact" className="inline-flex items-center gap-2 bg-blue-600 text-white px-6 py-3 rounded-lg font-bold hover:bg-blue-700 transition-colors">
              Start building <ArrowRight className="w-4 h-4" />
            </a>
            <a href="#features" className="inline-flex items-center gap-2 border border-slate-200 px-6 py-3 rounded-lg font-bold text-slate-700 hover:bg-slate-50 transition-colors">
              View system
            </a>
          </div>
        </div>
        <div className="bg-slate-900 text-white rounded-xl p-6 shadow-2xl">
          <p className="text-xs font-mono text-slate-400 mb-4">{'// builder pipeline'}</p>
          {{sections.map((section, index) => (
            <div key={{section}} className="flex items-center gap-4 py-3 border-b border-white/10 last:border-0">
              <span className="font-mono text-yellow-400 text-sm w-8">{{String(index + 1).padStart(2, '0')}}</span>
              <strong className="flex-1 text-sm">{{section}}</strong>
              <Check className="w-4 h-4 text-green-400" />
            </div>
          ))}}
        </div>
      </section>

      <section id="features" className="max-w-7xl mx-auto px-6 py-20">
        <div className="mb-8">
          <span className="text-xs font-bold uppercase tracking-widest text-blue-600">Core agents</span>
          <h2 className="mt-2 text-3xl font-bold text-slate-900">Small team, strong workflow.</h2>
        </div>
        <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-5">
          {{features.map((feature) => (
            <article key={{feature}} className="p-6 border border-slate-200 rounded-xl bg-white hover:shadow-lg transition-shadow">
              <Zap className="w-6 h-6 text-blue-600 mb-3" />
              <h3 className="font-bold text-slate-900 mb-1">{{feature}}</h3>
              <p className="text-sm text-slate-500">Designed for reliable generation, quick iteration, and readable output.</p>
            </article>
          ))}}
        </div>
      </section>

      <section id="pricing" className="max-w-7xl mx-auto px-6 py-20">
        <div className="grid md:grid-cols-2 gap-12 items-start">
          <div>
            <span className="text-xs font-bold uppercase tracking-widest text-blue-600">MVP stack</span>
            <h2 className="mt-2 text-3xl font-bold text-slate-900 mb-4">Built for local-first experimentation.</h2>
            <p className="text-slate-500 leading-relaxed">
              Ollama models, sandboxed tools, deterministic templates, and a repair loop around real terminal feedback.
            </p>
          </div>
          <ul className="space-y-3">
            {''.join(f'<li key="{component}" className="p-4 border-l-4 border-blue-600 bg-white rounded-lg font-bold text-slate-900 shadow-sm">{component}</li>' for component in components)}
          </ul>
        </div>
      </section>

      <section id="contact" className="max-w-7xl mx-auto px-6 py-20 text-center">
        <Mail className="w-8 h-8 text-blue-600 mx-auto mb-4" />
        <h2 className="text-3xl font-bold text-slate-900 mb-3">Ready for the next prompt.</h2>
        <p className="text-slate-500 mb-6">Generate, validate, repair, and preview without leaving your local machine.</p>
        <a href="mailto:hello@example.com" className="inline-flex items-center gap-2 bg-blue-600 text-white px-6 py-3 rounded-lg font-bold hover:bg-blue-700 transition-colors">
          Contact team
        </a>
      </section>
    </main>
  );
}}
"""

    return {
        "package.json": json.dumps(package_json, indent=2),
        "tsconfig.json": json.dumps(tsconfig_json, indent=2),
        "next.config.js": "/** @type {import('next').NextConfig} */\nconst nextConfig = {}\nmodule.exports = nextConfig\n",
        "tailwind.config.js": tailwind_config,
        "postcss.config.js": postcss_config,
        "src/app/layout.tsx": layout_tsx,
        "src/app/page.tsx": page_tsx,
        "src/app/globals.css": globals_css,
    }
