from __future__ import annotations

import json

from webbuilder.models import JsonDict


def render(requirements: JsonDict, plan: JsonDict) -> dict[str, str]:
    website_type = str(requirements.get("website_type", "Portfolio")).replace("_", " ").title()
    components = requirements.get("components", ["Header", "Hero", "About", "Projects", "Contact", "Footer"])

    index_html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{website_type}</title>
  <link rel="stylesheet" href="styles.css" />
</head>
<body>
  <header class="header">
    <div class="container header-inner">
      <a href="#" class="logo">{website_type}</a>
      <nav>
        <a href="#about">About</a>
        <a href="#projects">Projects</a>
        <a href="#contact">Contact</a>
      </nav>
    </div>
  </header>

  <section class="hero">
    <div class="container">
      <h1>Build something remarkable.</h1>
      <p>A clean, fast static site generated by WebForge autonomous builder.</p>
      <div class="actions">
        <a href="#projects" class="btn primary">View Projects</a>
        <a href="#contact" class="btn secondary">Get in Touch</a>
      </div>
    </div>
  </section>

  <section id="about" class="section">
    <div class="container">
      <h2>About</h2>
      <p>This site was autonomously generated from a single prompt using multi-agent AI orchestration.</p>
    </div>
  </section>

  <section id="projects" class="section projects">
    <div class="container">
      <h2>Projects</h2>
      <div class="grid">
        <div class="card">
          <h3>Project Alpha</h3>
          <p>Autonomous web builder powered by local AI models.</p>
        </div>
        <div class="card">
          <h3>Project Beta</h3>
          <p>Multi-agent system for code generation and validation.</p>
        </div>
        <div class="card">
          <h3>Project Gamma</h3>
          <p>Template-driven React application scaffold.</p>
        </div>
      </div>
    </div>
  </section>

  <section id="contact" class="section contact">
    <div class="container">
      <h2>Contact</h2>
      <p>Ready to build your next project?</p>
      <a href="mailto:hello@example.com" class="btn primary">Send Email</a>
    </div>
  </section>

  <footer class="footer">
    <div class="container">
      <p>&copy; 2024 {website_type}. Generated by WebForge.</p>
    </div>
  </footer>
</body>
</html>"""

    styles_css = """* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: system-ui, -apple-system, 'Segoe UI', sans-serif;
  color: #1a1a2e;
  background: #fafafa;
  line-height: 1.6;
}

.container {
  max-width: 1100px;
  margin: 0 auto;
  padding: 0 24px;
}

/* Header */
.header {
  position: sticky;
  top: 0;
  background: rgba(250, 250, 250, 0.95);
  backdrop-filter: blur(12px);
  border-bottom: 1px solid #e5e5e5;
  z-index: 100;
}
.header-inner {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 16px 24px;
}
.logo {
  font-weight: 800;
  font-size: 1.2rem;
  color: inherit;
  text-decoration: none;
}
.header nav {
  display: flex;
  gap: 24px;
}
.header nav a {
  color: #666;
  text-decoration: none;
  font-size: 0.9rem;
  transition: color 0.2s;
}
.header nav a:hover {
  color: #1a1a2e;
}

/* Hero */
.hero {
  padding: 100px 0 80px;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  color: white;
}
.hero h1 {
  font-size: 3.5rem;
  font-weight: 800;
  line-height: 1.1;
  margin-bottom: 16px;
}
.hero p {
  font-size: 1.2rem;
  opacity: 0.9;
  max-width: 500px;
  margin-bottom: 32px;
}
.actions {
  display: flex;
  gap: 12px;
}
.btn {
  display: inline-block;
  padding: 12px 24px;
  border-radius: 8px;
  font-weight: 700;
  text-decoration: none;
  transition: transform 0.2s, box-shadow 0.2s;
}
.btn:hover {
  transform: translateY(-2px);
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
}
.btn.primary {
  background: white;
  color: #667eea;
}
.btn.secondary {
  background: rgba(255, 255, 255, 0.2);
  color: white;
  border: 1px solid rgba(255, 255, 255, 0.3);
}

/* Sections */
.section {
  padding: 80px 0;
}
.section h2 {
  font-size: 2rem;
  font-weight: 800;
  margin-bottom: 16px;
}
.section p {
  color: #555;
  font-size: 1.1rem;
}

/* Projects Grid */
.projects .grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
  gap: 24px;
  margin-top: 32px;
}
.card {
  padding: 24px;
  border: 1px solid #e5e5e5;
  border-radius: 12px;
  background: white;
  transition: transform 0.2s, box-shadow 0.2s;
}
.card:hover {
  transform: translateY(-4px);
  box-shadow: 0 8px 24px rgba(0, 0, 0, 0.08);
}
.card h3 {
  font-weight: 700;
  margin-bottom: 8px;
}
.card p {
  color: #666;
  font-size: 0.95rem;
}

/* Contact */
.contact {
  text-align: center;
  background: #f5f5f5;
}

/* Footer */
.footer {
  padding: 32px 0;
  text-align: center;
  color: #999;
  font-size: 0.85rem;
  border-top: 1px solid #e5e5e5;
}

/* Responsive */
@media (max-width: 768px) {
  .hero h1 {
    font-size: 2.2rem;
  }
  .actions {
    flex-direction: column;
  }
  .header nav {
    gap: 16px;
  }
}
"""

    return {
        "index.html": index_html,
        "styles.css": styles_css,
    }
